/**
 * Cadence — Premium Audio Store
 * Static product data
 */

const PRODUCTS = [
  // ── HEADPHONES ───────────────────────────────────────────────────────
  {
    id: 1,
    name: "Planar Pro X",
    category: "Headphones",
    price: 1299,
    salePrice: null,
    description: "Open-back planar magnetic headphones engineered for reference-grade listening. 94mm driver diaphragm, lambskin ear cushions, and a laser-machined aluminium yoke. Frequency response 10–48kHz with ±1dB deviation.",
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    tags: ["New", "Bestseller"],
    specs: { driver: "94mm Planar Magnetic", impedance: "32Ω", weight: "380g", connectivity: "3.5mm / 6.35mm" },
    color: "#22D3EE",
    shape: "headphones-open"
  },
  {
    id: 2,
    name: "Apex Closed",
    category: "Headphones",
    price: 749,
    salePrice: 599,
    description: "Closed-back dynamic driver headphones with hybrid memory foam cups and custom 50mm beryllium-coated driver. Exceptional passive isolation makes it ideal for studio tracking and travel.",
    rating: 4.7,
    reviewCount: 218,
    inStock: true,
    tags: ["Sale"],
    specs: { driver: "50mm Beryllium Dynamic", impedance: "25Ω", weight: "295g", connectivity: "Detachable 3.5mm" },
    color: "#3B82F6",
    shape: "headphones-closed"
  },
  {
    id: 3,
    name: "Void Wireless",
    category: "Headphones",
    price: 449,
    salePrice: null,
    description: "Bluetooth 5.3 over-ear headphones with aptX Lossless and ANC. 40-hour battery life, USB-C fast charge (10 min = 3 hours), and a folding aluminium frame. No audible compromise.",
    rating: 4.5,
    reviewCount: 487,
    inStock: true,
    tags: ["Bestseller"],
    specs: { driver: "40mm Dynamic", impedance: "18Ω", weight: "260g", connectivity: "Bluetooth 5.3 / USB-C" },
    color: "#6366F1",
    shape: "headphones-wireless"
  },
  {
    id: 4,
    name: "Studio One",
    category: "Headphones",
    price: 199,
    salePrice: null,
    description: "The professional's workhorse. Semi-open back, flat frequency response, and swivelling ear cups for single-ear monitoring. Used in broadcast studios worldwide.",
    rating: 4.6,
    reviewCount: 901,
    inStock: false,
    tags: ["New"],
    specs: { driver: "45mm Dynamic", impedance: "40Ω", weight: "310g", connectivity: "Coiled 3.5mm + 6.35mm adaptor" },
    color: "#A855F7",
    shape: "headphones-studio"
  },

  // ── SPEAKERS ─────────────────────────────────────────────────────────
  {
    id: 5,
    name: "Forma Two",
    category: "Speakers",
    price: 1890,
    salePrice: null,
    description: "A bookshelf speaker that doesn't accept the term 'bookshelf'. Aluminium cone woofer, soft-dome tweeter, rear-ported cabinet in solid walnut. Sold as a pair. Will re-define your room.",
    rating: 4.9,
    reviewCount: 143,
    inStock: true,
    tags: ["Bestseller"],
    specs: { woofer: "5.5\" Aluminium Cone", tweeter: "1\" Soft Dome", power: "80W/ch RMS", frequency: "48Hz–25kHz" },
    color: "#22D3EE",
    shape: "speaker-bookshelf"
  },
  {
    id: 6,
    name: "Node Compact",
    category: "Speakers",
    price: 399,
    salePrice: 319,
    description: "Wireless multi-room speaker with 360° sound dispersion. AirPlay 2, Spotify Connect, Bluetooth 5.0. Fabric mesh enclosure, RGB ambient ring (disable it — the sound is the point).",
    rating: 4.4,
    reviewCount: 672,
    inStock: true,
    tags: ["Sale"],
    specs: { drivers: "2×2\" + 1×3.5\"", power: "2×20W + 30W", frequency: "60Hz–22kHz", connectivity: "Wi-Fi / Bluetooth" },
    color: "#3B82F6",
    shape: "speaker-round"
  },
  {
    id: 7,
    name: "Column Floor",
    category: "Speakers",
    price: 4200,
    salePrice: null,
    description: "Floor-standing 3-way tower loudspeaker. Bi-wire/bi-amp terminals, reflex-tuned bass cabinet, and a ribbon tweeter for air that dynamic drivers can't replicate. Presence in any room.",
    rating: 4.8,
    reviewCount: 56,
    inStock: true,
    tags: [],
    specs: { woofer: "2×7\" Paper Cone", midrange: "4\" Kevlar", tweeter: "Ribbon AMT", power: "250W Continuous" },
    color: "#10B981",
    shape: "speaker-tower"
  },
  {
    id: 8,
    name: "Pulse Bar",
    category: "Speakers",
    price: 699,
    salePrice: null,
    description: "A soundbar that knows it's not a substitute for real speakers. Dolby Atmos, optical + HDMI eARC, six-channel room calibration. For when your TV audio is genuinely embarrassing.",
    rating: 4.3,
    reviewCount: 338,
    inStock: false,
    tags: [],
    specs: { channels: "3.1.2", power: "7×40W", connectivity: "HDMI eARC / Optical / Bluetooth", calibration: "6-mic auto EQ" },
    color: "#F59E0B",
    shape: "speaker-bar"
  },

  // ── TURNTABLES ───────────────────────────────────────────────────────
  {
    id: 9,
    name: "Orbit Carbon",
    category: "Turntables",
    price: 649,
    salePrice: null,
    description: "Belt-drive turntable with carbon fibre tonearm and Ortofon 2M Red cartridge pre-installed. Motor decoupled chassis eliminates rumble. Plays 33⅓ and 45 RPM. No Bluetooth. No compromises.",
    rating: 4.8,
    reviewCount: 891,
    inStock: true,
    tags: ["Bestseller"],
    specs: { drive: "Belt Drive", tonearm: "Carbon Fibre 8.6\"", cartridge: "Ortofon 2M Red", speeds: "33⅓ / 45 RPM" },
    color: "#22D3EE",
    shape: "turntable"
  },
  {
    id: 10,
    name: "Platter One",
    category: "Turntables",
    price: 1499,
    salePrice: null,
    description: "Direct-drive DJ/audiophile crossover with quartz-locked motor, aluminium die-cast platter and a universally-praised isolation platform. Tonearm upgradeable. Built for longevity.",
    rating: 4.7,
    reviewCount: 204,
    inStock: true,
    tags: ["New"],
    specs: { drive: "Direct Drive", motor: "Quartz Locked", platter: "335mm Die-Cast Alloy", speeds: "33⅓ / 45 / 78 RPM" },
    color: "#6366F1",
    shape: "turntable-pro"
  },
  {
    id: 11,
    name: "Debut Carbon Evo",
    category: "Turntables",
    price: 499,
    salePrice: 419,
    description: "The evolution of a beloved entry point. Anti-resonance MDF plinth with elastomer feet, upgraded carbon tonearm, and a precision stylus. Compatible with most phono stages.",
    rating: 4.6,
    reviewCount: 1203,
    inStock: true,
    tags: ["Sale", "Bestseller"],
    specs: { drive: "Belt Drive", tonearm: "Carbon 8.6\"", speeds: "33⅓ / 45 RPM", phono: "MM Stage Optional" },
    color: "#A855F7",
    shape: "turntable-entry"
  },

  // ── ACCESSORIES ──────────────────────────────────────────────────────
  {
    id: 12,
    name: "Phono Stage III",
    category: "Accessories",
    price: 329,
    salePrice: null,
    description: "MM/MC-compatible solid-state phono preamplifier with RIAA-accurate EQ, ultra-low noise floor (−102dBV), and precision subsonic filter. Separate linear power supply included.",
    rating: 4.7,
    reviewCount: 177,
    inStock: true,
    tags: ["New"],
    specs: { compatibility: "MM / MC", noise: "−102dBV", output: "RCA Stereo", power: "Linear PSU Included" },
    color: "#22D3EE",
    shape: "phono-stage"
  },
  {
    id: 13,
    name: "Kinetic DAC",
    category: "Accessories",
    price: 599,
    salePrice: null,
    description: "MQA-certified DAC/headphone amplifier. ESS Sabre 9038 chip, balanced 4.4mm Pentaconn output, native DSD512 and PCM 768kHz. A transparent window into your digital library.",
    rating: 4.8,
    reviewCount: 298,
    inStock: true,
    tags: ["Bestseller"],
    specs: { chip: "ESS Sabre 9038", outputs: "4.4mm / 6.35mm / RCA", resolution: "DSD512 / 32bit 768kHz", formats: "MQA / FLAC / WAV" },
    color: "#3B82F6",
    shape: "dac"
  },
  {
    id: 14,
    name: "Meridian Cables",
    category: "Accessories",
    price: 149,
    salePrice: 99,
    description: "Balanced XLR interconnects with silver-plated copper conductors, low-capacitance dielectric, and Neutrik connectors. 1m pair. What you put between your gear matters.",
    rating: 4.5,
    reviewCount: 412,
    inStock: true,
    tags: ["Sale"],
    specs: { conductor: "Silver-Plated OFC", connector: "Neutrik XLR", length: "1m Pair", capacitance: "47pF/m" },
    color: "#6366F1",
    shape: "cable"
  },
  {
    id: 15,
    name: "Vinyl Care Kit",
    category: "Accessories",
    price: 89,
    salePrice: null,
    description: "The complete record maintenance kit: anti-static carbon fibre brush, microfibre cleaning cloth, stylus cleaning gel, and record sleeves (50 pack). Protect your collection.",
    rating: 4.6,
    reviewCount: 823,
    inStock: true,
    tags: [],
    specs: { includes: "Carbon Brush, Stylus Gel, Cloth", sleeves: "50× Anti-Static PE", brush: "Carbon Fibre 4cm", gel: "25ml Stylus Cleaner" },
    color: "#10B981",
    shape: "kit"
  },
  {
    id: 16,
    name: "Stand Mount Pro",
    category: "Accessories",
    price: 279,
    salePrice: null,
    description: "Rigid steel speaker stands with sand/shot-fillable columns, spiked feet, and cable management channels. Adjustable top plate (140×140 to 220×220mm). Pair. Worth every penny.",
    rating: 4.4,
    reviewCount: 189,
    inStock: true,
    tags: [],
    specs: { material: "14-Gauge Steel", height: "60cm Adjustable", topPlate: "Up to 220×220mm", weight: "12kg/pair" },
    color: "#F59E0B",
    shape: "stand"
  }
];
